cosmo: [CMB_ODT, GL_Xray, BBN_Neff, BBN_D, CMB_EBLright, EBL_Ressell, GL_Grin, EBL_gEBL1,
  EBL_Over, CMB_DEsu, CMB_mu]
fill: [GB, CMB_ODT, GL_Xray, BBN_Neff, BBN_D, CMB_EBLright, EBL_Ressell, GL_Grin,
  EBL_gEBL1, EBL_Over, CMB_DEsu, CMB_mu, HB, SUN, curve_fischer_with_degeneracy_and_mass_effects_18Msun_jf,
  cast_env_2016, limits_cgrh, BeamDump_SLACE141, BeamDump_SLAC137, ep_invisible, LSW_combi,
  LSW_llElip, fermi-SN, fermi-lat1, WDcool, mWD_3, mWD_2, mWD_1, ll_opacity_FR1p3_IGMF+ICM,
  curve_fischer_with_degeneracy_and_mass_effects_18Msun_jf, CTA_Opac_3sigma_B50_AllSrc,
  IAXO_CAST_scaled, ALPSII, CTA_50hrs_NGC1275, CTA_veritas_q0p95_cl0p95]
fill_between: [llrbf, ADMX, axion_hf, constraint_hess_cluster, constraint_hess_igmf,
  ngc1275_x-ray, ngc1275_strobe-x, Madmax-80d-1m2-5e4-10T, Madmax-20d-20cm-3T, Madmax-4d-20cm-2T,
  GC, fermi_exgal_sne]
hint: [WDcool, ll_opacity_FR1p3_IGMF+ICM]
plot: [LHAASO_2sigmaExclB5, LHAASO_2sigmaExclB3]
sens: [CTA_Opac_3sigma_B50_AllSrc, CTA_50hrs_NGC1275, CTA_veritas_q0p95_cl0p95, ngc1275_strobe-x,
  x-ray_alp_limits, Madmax-80d-1m2-5e4-10T, Madmax-20d-20cm-3T, Madmax-4d-20cm-2T,
  LHAASO_2sigmaExclB5, LHAASO_2sigmaExclB3, IAXO_CAST_scaled, ALPSII, fermi-SN]
